name: Echo Comments

on:
  issue_comment:
    types: [created]
    
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    
    - name: echo into new comment
      id: echo
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo } = context.repo;
          const { number: issue_number } = context.payload.issue;
          const { body } = context.payload.comment;
          const result = await github.rest.issues.createComment({ owner, repo, issue_number, body });
          return result.data;
        
    - name: write results
      id: results
      shell: bash
      run: |
        cat "${{ steps.echo.outputs.result }}" > result.json
        echo "URL=$(cat result.json | jq -r .url)" >> $GITHUB_ENV
        echo "HTML_URL=$(cat result.json | jq -r .html_url)" >> $GITHUB_ENV
        
    - name: env
      shell: bash
      run: env | sort
    
